### ISSUE TITLE
How to handle 'Push button' using a 'Blue Pill' board?

### ISSUE THREAD

**Issue by Terbium-135** [gl-sergei/u2f-token#19]
Thank you very much for this nice project though I am kinda stuck..

With https://fidodemo.strongauth.com/fidorestapp/action for U2F testing I can't figure out how the 'push button' situation is handled using a STM32F103 board

**Comment by gl-sergei** [comment]
First of all, you can solder the push button and create a new target device (see https://github.com/gl-sergei/chopstx/blob/master/board/board-maple-mini.h for example of STM32F103 with the push button).

If you are using the build for BLUE_PILL target, it is set up so that user presence is indicated first 10 seconds after power up or reset. I.e. you can use reset button or unplug and re-plug the device when asked to push the button.
